language: python
dist: trusty
sudo: false
python: 2.7_with_system_site_packages
addons:
  apt:
    packages:
      - python-gdal
      - python-numpy
      - libhdf5-serial-dev
install:
    - pip install -r requirements.txt -r test_requirements.txt -i https://pypi.pacificclimate.org/simple/
    - pip install -i https://pypi.pacificclimate.org/simple/ .
script:
    - py.test
