language: python
python: 2.7_with_system_site_packages
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-gdal python-numpy libhdf5-serial-dev
install:
    - pip install -r requirements.txt -r test_requirements.txt -i http://tools.pacificclimate.org/pypiserver/
    - pip install -i http://tools.pacificclimate.org/pypiserver/ .
script:
    - py.test
